Repository milieuinfo/webcomponent-vl-ui-header, pull requests merged in 2020-04, with the labels that each got.

#18 Introductie data-vl-development attribuut voor lokale ontwikkeling
  demo/vl-header.html
  src/vl-header.js
  test/unit/vl-header.test.html
Labels: bug, enhancement

#14 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#20 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore
